runtime: python27
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

runtime_config:
    python_version: 2.7

handlers:
- url: /.*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: find-210623:us-central1:lambda-instance
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: init.lambda

libraries:
- name: MySQLdb
  version: "latest"
- name: flask
  version: 0.12
- name: jinja2
  version: 2.6
- name: werkzeug
  version: 0.11.10
